from .cita_medica import Citamedica
from .comuna import Comuna
from .direccion import Direccion
from .doctor import Doctor
from .especialidad import Especialidad
from .ficha_clinica import FichaClinica
from .orden_examenes import OrdenExamenes
from .paciente import Paciente
from .receta_medica import RecetaMedica
from .turno import Turno
